### ISSUE TITLE
Add to README: Does this tool collect IP addresses? What info does this tool collect?

### ISSUE THREAD

**Issue by unsocial-bleach** [Jobcrazy/BitTorrent-DHT-Spider#1]
It would be helpful if a more specific listing of the data collected was given in the README. Does this tool collect IP addresses of users, or is it focused on the torrents only.

**Comment by Jobcrazy** [comment]
> It would be helpful if a more specific listing of the data collected was given in the README. Does this tool collect IP addresses of users, or is it focused on the torrents only.

Thank you for suggestion. It will just collect the magnet links from torrent files and save them to the database. 

As you can't hide your IP without proxy in the DHT network, so you could turen to turn to libtorrent for help if you want to collect IP addresses.
